In [1]:
import numpy as np
from scipy.signal import convolve2d

class Convolution2D:
    def __init__(self, input_image=None, filter_kernel=None):
        self.input_image = input_image
        self.filter_kernel = filter_kernel
        self.output_image = None

    def set_input_image(self, input_image):
        self.input_image = input_image

    def set_filter_kernel(self, filter_kernel):
        self.filter_kernel = filter_kernel

    def perform_convolution(self):
        if self.input_image is None or self.filter_kernel is None:
            raise ValueError("Input image and filter kernel must be set before performing convolution.")

        input_shape = self.input_image.shape
        kernel_shape = self.filter_kernel.shape

        output_shape = (input_shape[0] - kernel_shape[0] + 1,
                        input_shape[1] - kernel_shape[1] + 1)
        self.output_image = np.zeros(output_shape)

        for i in range(output_shape[0]):
            for j in range(output_shape[1]):
                self.output_image[i, j] = np.sum(self.input_image[i:i+kernel_shape[0], j:j+kernel_shape[1]] * self.filter_kernel)

        return self.output_image

    def perform_depthwise_convolution(self):
        if self.input_image is None or self.filter_kernel is None:
            raise ValueError("Input image and filter kernel must be set before performing depthwise convolution.")

        output = np.zeros_like(self.input_image)
        for channel in range(self.input_image.shape[2]):
            for i in range(self.filter_kernel.shape[2]):
                output[:, :, channel] += convolve2d(self.input_image[:, :, channel], self.filter_kernel[:, :, i, 0], mode='same', boundary='wrap')
        self.output_image = output
        return self.output_image

    def perform_pointwise_convolution(self):
        if self.input_image is None or self.filter_kernel is None:
            raise ValueError("Input image and filter kernel must be set before performing pointwise convolution.")

        expanded_image = self.input_image[:, :, :, np.newaxis] 
        output = np.sum(expanded_image * self.filter_kernel, axis=2) 
        self.output_image = output
        return self.output_image

if __name__ == "__main__":
    conv2d = Convolution2D()

    # Setup for a basic convolution operation
    original_image = np.random.rand(6, 6, 1)  # Simulated single-channel image
    filter_kernel = np.random.rand(3, 3, 1, 1)  # Simulated depthwise kernel for a single channel
    conv2d.set_input_image(original_image)
    conv2d.set_filter_kernel(filter_kernel)

    depthwise_output = conv2d.perform_depthwise_convolution()
    print("Depthwise Convolution Output:\n", depthwise_output)



Depthwise Convolution Output:
 [[[3.16126057]
  [3.19809621]
  [3.10524512]
  [3.07431487]
  [3.02295306]
  [3.38527805]]

 [[3.72665945]
  [4.19640419]
  [3.16826691]
  [3.49660912]
  [2.74596644]
  [3.78955654]]

 [[3.12408894]
  [3.33937035]
  [2.74094273]
  [3.15639923]
  [3.40666049]
  [3.47120003]]

 [[2.38245166]
  [2.94921254]
  [2.26378002]
  [2.40626158]
  [2.73570484]
  [2.45941164]]

 [[2.15040542]
  [1.56825766]
  [2.07191285]
  [2.20501623]
  [2.73280333]
  [2.14148455]]

 [[2.56911888]
  [1.98218656]
  [2.34288628]
  [2.40935397]
  [2.13186008]
  [3.08323679]]]
